/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package sa.sauditourism.employee.huawei;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType AccountTabHuaweiModel.
 *
 * @since 2024-06-05
 */
@PrimaryKeys({"index"})
public final class AccountTabHuaweiModel extends CloudDBZoneObject {
    private Integer index;

    @NotNull
    @DefaultValue(stringValue = "")
    private String id;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean show;

    @NotNull
    @DefaultValue(stringValue = "NON_PROD")
    private String environment;

    public AccountTabHuaweiModel() {
        super(AccountTabHuaweiModel.class);
        this.id = "";
        this.show = false;
        this.environment = "NON_PROD";
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public Integer getIndex() {
        return index;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setShow(Boolean show) {
        this.show = show;
    }

    public Boolean getShow() {
        return show;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getEnvironment() {
        return environment;
    }

}
