/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package sa.sauditourism.employee.huawei;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import sa.sauditourism.employee.constants.FirebaseConstants;

import sa.sauditourism.employee.constants.FirebaseConstants;


/**
 * Definition of ObjectType AppMaintenanceHuawei.
 *
 * @since 2024-04-16
 */
@PrimaryKeys({"id"})
public final class AppMaintenanceHuawei extends CloudDBZoneObject {
    private Integer id;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean enable;

    @NotNull
    @DefaultValue(stringValue = "")
    private String version;

    @DefaultValue(stringValue = "PROD")
    private String environment;

    public AppMaintenanceHuawei() {
        super(AppMaintenanceHuawei.class);
        this.enable = false;
        this.version = "";
        this.environment = FirebaseConstants.REALTIME_DB_PROD_VALUE;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public Boolean getEnable() {
        return enable;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getVersion() {
        return version;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getEnvironment() {
        return environment;
    }

}
