/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package sa.sauditourism.employee.resources.theme.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import sa.sauditourism.employee.constants.FirebaseConstants;


/**
 * Definition of ObjectType AppTheme.
 *
 * @since 2024-04-16
 */
@PrimaryKeys({"id"})
public final class AppTheme extends CloudDBZoneObject {
    private Integer id;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean isActive;

    private String darkPrimary;

    private String darkSecondary;

    private String lightPrimary;

    private String lightSecondary;

    @DefaultValue(stringValue = "PROD")
    private String environment;

    public AppTheme() {
        super(AppTheme.class);
        this.isActive = false;
        this.environment = FirebaseConstants.REALTIME_DB_PROD_VALUE;
    }

    public AppTheme(String primaryDark, String primaryLight, String secondaryDark, String secondaryLight, String environment) {
        super(AppTheme.class);
        this.isActive = false;
        this.darkPrimary = primaryDark;
        this.lightPrimary = primaryLight;
        this.darkSecondary = secondaryDark;
        this.lightSecondary = secondaryLight;
        this.environment = environment;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setDarkPrimary(String darkPrimary) {
        this.darkPrimary = darkPrimary;
    }

    public String getDarkPrimary() {
        return darkPrimary;
    }

    public void setDarkSecondary(String darkSecondary) {
        this.darkSecondary = darkSecondary;
    }

    public String getDarkSecondary() {
        return darkSecondary;
    }

    public void setLightPrimary(String lightPrimary) {
        this.lightPrimary = lightPrimary;
    }

    public String getLightPrimary() {
        return lightPrimary;
    }

    public void setLightSecondary(String lightSecondary) {
        this.lightSecondary = lightSecondary;
    }

    public String getLightSecondary() {
        return lightSecondary;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getEnvironment() {
        return environment;
    }

}
