package sa.sauditourism.employee.constants

object LanguageConstants {
    const val DEFAULT_LOCALE = "en"
    const val LANG_AR = "ar"
    const val SUPPORTED_LANGUAGE_CODE = "code"
    const val SUPPORTED_LANGUAGE_ENV = "env"
    const val SUPPORTED_LANGUAGE_FLAG = "flag"
    const val SUPPORTED_LANGUAGE_ID = "id"
    const val SUPPORTED_LANGUAGE_VALUE = "value"
    const val SUPPORTED_LANGUAGE_TABS = "tabs"
    const val FIREBASE_LANGUAGE_DATABASE_NAME = "locale"
    const val FIREBASE_SUPPORTED_LANGUAGES_DATABASE_NAME = "supportedLanguages"
    const val HUAWEI_CLOUD_DB_ZONE = "VisitSaudi"
    const val FIREBASE_SERVICES_DATABASE_NAME = "services"
    const val FIREBASE_ONBOARDING_DATABASE_NAME = "onboarding"
    const val FIREBASE_ONBOARDING_AR_DATABASE_NAME = "onboardingAr"

    const val UPDATE_REQUIRED = "UPDATE_REQUIRED"
    const val UPDATE_REQUIRED_DESCRIPTION = "UPDATE_REQUIRED_DESCRIPTION"
    const val UPDATE_LATER = "UPDATE_LATER"
    const val UPDATE_NOW = "UPDATE_NOW"

    const val HOME_TAB = "HOME_TAB"
    const val SERVICES_TAB = "SERVICES_TAB"
    const val PEOPLE_TAB = "PEOPLE_TAB"
    const val ACCOUNT_TAB = "ACCOUNT_TAB"

    const val LOGIN_TITLE = "LOGIN_TITLE"
    const val LOGIN_SUBTITLE = "LOGIN_SUBTITLE"
    const val LOGIN_BUTTON_TITLE = "LOGIN_BUTTON_TITLE"
    const val LOGIN_CHANGE_PASSWORD_TITLE = "LOGIN_CHANGE_PASSWORD_TITLE"
    const val CHANGE_LANGUAGE_TITLE = "CHANGE_LANGUAGE_TITLE"
    const val DONE_BUTTON_TITLE = "DONE_BUTTON_TITLE"

    const val SEARCH_FOR_REQUESTS = "SEARCH_FOR_REQUESTS"
    const val SERVICES_CATEGORIES = "SERVICES_CATEGORIES"

    //error handling language constants
    const val UNEXPECTED_ERROR_HAS_OCCURRED = "UNEXPECTED_ERROR_HAS_OCCURRED"
    const val NO_CONNECTION = "NO_CONNECTION"
    const val NO_CONNECTION_MESSAGE = "NO_CONNECTION_MESSAGE"
    const val TRY_AGAIN = "TRY_AGAIN"
    const val FORBIDDEN_MESSAGE = "FORBIDDEN_MESSAGE"
    const val ERROR_TITLE = "ERROR_TITLE"
    const val RETRY = "RETRY"
    const val CANCEL = "CANCEL"
    const val SEARCH_RESULT_EMPTY_TITLE = "SEARCH_RESULT_EMPTY_TITLE"
    const val SEARCH_RESULT_EMPTY_DESCRIPTION = "SEARCH_RESULT_EMPTY_DESCRIPTION"

    //EMPTY VIEW
    const val NO_RESULT_FOUND = "NO_RESULT_FOUND"
    const val NO_RESULT_FOUND_MESSAGE = "NO_RESULT_FOUND_MESSAGE"

    const val NOTE = "NOTE"
    const val OPTIONAL = "OPTIONAL"
    const val SUBMIT = "SUBMIT"
    const val SECURITY_POPUP_TITLE = "SECURITY_POPUP_TITLE"
    const val SECURITY_POPUP_DESCRIPTION = "SECURITY_POPUP_DESCRIPTION"

    const val MOBILE_UNDER_MAINTENANCE = "MOBILE_UNDER_MAINTENANCE"
    const val MOBILE_UNDER_MAINTENANCE_DESCRIPTION = "MOBILE_UNDER_MAINTENANCE_DESCRIPTION"

    const val TOAST_CONNECTION = "TOAST_CONNECTION"
    const val TOAST_CONNECTION_MESSAGE = "TOAST_CONNECTION_MESSAGE"

    const val SEARCH_HERE = "SEARCH_HERE"
    const val SEARCH = "SEARCH"
    const val NONE = "NONE"

    //Account
    const val ACCOUNT_SIGN_OUT = "ACCOUNT_SIGN_OUT"
    const val ACCOUNT_SIGN_OUT_ALERT_SUBTITLE = "ACCOUNT_SIGN_OUT_ALERT_SUBTITLE"
    const val ACCOUNT_SIGN_OUT_ALERT_TITLE = "ACCOUNT_SIGN_OUT_ALERT_TITLE"
    const val ACCOUNT_VERSION = "ACCOUNT_VERSION"
    const val ACCOUNT_SETTINGS = "ACCOUNT_SETTINGS"
    const val ACCOUNT_ID = "ACCOUNT_ID"
    const val ACCOUNT_SHOW_MY_BUSINESS_CARD = "ACCOUNT_SHOW_MY_BUSINESS_CARD"
    const val ACCOUNT_SHARE_MY_BUSINESS_CARD = "ACCOUNT_SHARE_MY_BUSINESS_CARD"
    const val ACCOUNT_SHARE = "ACCOUNT_SHARE"
    const val ACCOUNT_EMPLOYEE_DETAILS = "ACCOUNT_EMPLOYEE_DETAILS"
    const val ACCOUNT_EMPLOYEE_NAME = "ACCOUNT_EMPLOYEE_NAME"
    const val ACCOUNT_EMPLOYEE_EMAIL = "ACCOUNT_EMPLOYEE_EMAIL"
    const val ACCOUNT_EMPLOYEE_PHONE = "ACCOUNT_EMPLOYEE_PHONE"
    const val ACCOUNT_EMPLOYEE_JOB_TITLE = "ACCOUNT_EMPLOYEE_JOB_TITLE"
    const val ACCOUNT_MY_PERSONAL_PROFILE = "ACCOUNT_MY_PERSONAL_PROFILE"
    const val ACCOUNT_MY_LEAVES = "ACCOUNT_MY_LEAVES"
    const val ACCOUNT_MY_PAYSLIP = "ACCOUNT_MY_PAYSLIP"
    const val ACCOUNT_MY_REQUESTS = "ACCOUNT_MY_REQUESTS"
    const val ACCOUNT_BUSINESS_CARD_SCREEN_TITLE = "ACCOUNT_BUSINESS_CARD_SCREEN_TITLE"
    const val ACCOUNT_JOB_TITLE = "ACCOUNT_JOB_TITLE"
    const val ACCOUNT_DEPARTMENT = "ACCOUNT_DEPARTMENT"
    const val ACCOUNT_PREFERRED_LANGUAGE = "ACCOUNT_PREFERRED_LANGUAGE"


    const val CAMERA_USER_PERMISSION = "CAMERA_USER_PERMISSION"
    const val ATTACHEMNT_SELECT_UPLOAD_OPTION = "ATTACHEMNT_SELECT_UPLOAD_OPTION"
    const val ATTACHEMNT_SELECT_PHOTO_LIBRARY = "ATTACHEMNT_SELECT_PHOTO_LIBRARY"
    const val ATTACHEMNT_SELECT_DOCUMENT_LIBRARY = "ATTACHEMNT_SELECT_DOCUMENT_LIBRARY"
    const val ATTACHEMNT_SELECT_CAMERA = "ATTACHEMNT_SELECT_CAMERA"
    const val ATTACHEMNT_DESCRIPTION = "ATTACHEMNT_DESCRIPTION"
    const val ATTACHEMNT_MAX_SIZE = "ATTACHEMNT_MAX_SIZE"

    const val NEXT = "NEXT"
    const val BACK = "BACK"
    const val SKIP = "SKIP"
    const val TIME = "TIME"

    const val ACCOUNT_UPDATE_BUTTON = "ACCOUNT_UPDATE_BUTTON"

    //coming soon
    const val COMING_SOON = "COMING_SOON"
    const val PEOPLE_TAB_COMING_SOON_SUBTITLE = "PEOPLE_TAB_COMING_SOON_SUBTITLE"

    const val FORM_SUCCESS_TITLE = "FORM_SUCCESS_TITLE"
    const val FORM_SUCCESS_MESSAGE = "FORM_SUCCESS_MESSAGE"

    // My Requests
    const val MY_REQUESTS = "My_REQUESTS"
    const val ID = "ID"
    const val REQUEST_ACTIVITY = "REQUEST_ACTIVITY"
    const val ADD_COMMENT = "ADD_COMMENT"

    const val VIEW_ACTIVITIES = "VIEW_ACTIVITIES"
    const val REQUEST_DETAILS = "REQUEST_DETAILS"
    const val DELETE = "DELETE"
    const val EDIT = "EDIT"

    const val SUCCESS_TITLE = "Success Title"
    const val SUCCESS_MESSAGE = "Success Message"

    const val ATTACHMENT = "Attachment"
    const val SEND = "SEND"
    const val MESSAGE_ATTACHMENT = "Message text goes here."

    const val SHARE_BUSINESS_CARD = "SHARE_BUSINESS_CARD"
    const val SCAN_QR_CODE = "SCAN_QR_CODE"

    const val MY_PAY_SLIP = "MY_PAY_SLIP"
    const val FILTER = "FILTER"
    const val SELECT_MONTH = "SELECT_MONTH"
    const val SELECT_YEAR = "SELECT_YEAR"
    const val CHOOSE_MONTH = "CHOOSE_MONTH"
    const val CHOOSE_YEAR = "CHOOSE_YEAR"
    const val SAVE = "SAVE"
    const val CHOOSE_SERVICE_CATEGORY = "CHOOSE_SERVICE_CATEGORY"
    const val CREATED_BY_ME = "CREATED_BY_ME"
    const val ASSIGNED_TO_ME = "ASSIGNED_TO_ME"

    const val DELETE_MESSAGE = "DELETE_MESSAGE"
    const val PARTICIPANTS_HEADER_TITLE = "PARTICIPANTS_HEADER_TITLE"
    const val ADD_PARTICIPANTS_BUTTON_TITLE = "ADD_PARTICIPANTS_BUTTON_TITLE"
    const val ADD_NEW_PARTICIPANT = "ADD_NEW_PARTICIPANT"
    const val PARTICIPANTS = "PARTICIPANTS"

    const val ATTACHMENT_SIZE_VALIDATION_ERROR_TITLE = "ATTACHMENT_SIZE_VALIDATION_ERROR_TITLE"
    const val ATTACHMENT_SIZE_VALIDATION_ERROR_DESCRIPTION =
        "ATTACHMENT_SIZE_VALIDATION_ERROR_DESCRIPTION"

    const val SELECT_YOUR_PROFILE_PICTURE = "SELECT_YOUR_PROFILE_PICTURE"
    const val CHOOSE_IMAGE_FROM_GALLERY = "CHOOSE_IMAGE_FROM_GALLERY"
    const val TAKE_PHOTO = "TAKE_PHOTO"
    const val REMOVE_CURRENT_PICTURE = "REMOVE_CURRENT_PICTURE"
    const val CHOOSE_AN_AVATAR = "CHOOSE_AN_AVATAR"
    const val ADD_IMAGE = "ADD_IMAGE"
    const val YOUR_PICTURE_CHANGED_SUCCESSFULLY = "YOUR_PICTURE_CHANGED_SUCCESSFULLY"
    const val YOUR_PICTURE_IS_NOW_DELETED = "YOUR_PICTURE_IS_NOW_DELETED"

    const val OK = "OK"
    const val HI = "HI"

    const val MY_DAY_TITLE = "MY_DAY_TITLE"
    const val HAPPENING_TODAY_TITLE = "HAPPENING_TODAY_TITLE"
    const val HAPPENING_TODAY_SUBTITLE = "HAPPENING_TODAY_SUBTITLE"
    const val NO_ANNOUNCEMENTS_FOUND = "NO_ANNOUNCEMENTS_FOUND"
    const val ATTACHMENTS = "ATTACHMENTS"
    const val SCANQR = "SCANQR"
    const val QRCODE = "QRCODE"

    // for book a Meeting Room
    const val BOOK_MEETING_ROOM_TITLE = "BOOK_MEETING_ROOM_TITLE"
    const val FROM = "FROM"
    const val TO = "TO"
    const val AVAILABLE_MEETING_ROOM_BUTTON_TITLE = "AVAILABLE_MEETING_ROOM_BUTTON_TITLE"
    const val INVALID_MEETING_DURATION = "INVALID_MEETING_DURATION"
    const val INVALID_TIME_INTERVAL = "INVALID_TIME_INTERVAL"

    // for check available meeting rooms
    const val AVAILABLITY_TITLE = "AVAILABLITY_TITLE"
    const val AVAILABILITY_SUBTITLE = "AVAILABILITY_SUBTITLE"
    const val SEARCH_FOR_MEETING_ROOMS = "SEARCH_FOR_MEETING_ROOMS"
    const val FLOOR_1 = "FLOOR_1"
    const val FLOOR_2 = "FLOOR_2"
    const val FLOOR_3 = "FLOOR_3"
    const val TH_FLOOR = "TH_FLOOR"
    const val FLOOR = "FLOOR"
    const val SORRY = "SORRY"
    const val NO_ROOMS_AVAILABLE = "NO_ROOMS_AVAILABLE"

    // for single room feature
    const val ROOM_CAPACITY = "ROOM_CAPACITY"
    const val ROOM_FEATURES = "ROOM_FEATURES"
    const val MEETING_TITLE = "MEETING_TITLE"
    const val BOOK_ROOM = "BOOK_ROOM"
    const val ROOM_DESCRIPTION = "ROOM_DESCRIPTION"
    const val MEETING_DATE = "MEETING_DATE"
    const val MEETING_DESCRIPTION = "MEETING_DESCRIPTION"
    const val MEETING_IS_BOOKED = "MEETING_IS_BOOKED"
    const val TIME_HAS_ALREADY_PASSED = "TIME_HAS_ALREADY_PASSED"
    const val TIME_TAKEN_ERROR_TITLE = "TIME_TAKEN_ERROR_TITLE"
    const val TIME_TAKEN_ERROR_DESCRIPTION = "TIME_TAKEN_ERROR_DESCRIPTION"

    //successfully booked screen
    const val BACK_TO_MY_DAY = "BACK_TO_MY_DAY"
    const val SUCCESSFULLY_BOOKED_ROOM = "SUCCESSFULLY_BOOKED_ROOM"
    const val IN = "IN"




}

