/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package sa.sauditourism.employee.managers.language.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import sa.sauditourism.employee.constants.FirebaseConstants;


/**
 * Definition of ObjectType AppLang.
 *
 * @since 2024-04-16
 */
@PrimaryKeys({"id"})
public final class AppLang extends CloudDBZoneObject {
    private Integer id;

    @NotNull
    @DefaultValue(textValue = "")
    private Text content;

    @NotNull
    @DefaultValue(stringValue = "")
    private String code;

    @DefaultValue(stringValue = "PROD")
    private String environment;

    public AppLang() {
        super(AppLang.class);
        this.content = new Text("");
        this.code = "";
        this.environment = FirebaseConstants.REALTIME_DB_PROD_VALUE;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setContent(Text content) {
        this.content = content;
    }

    public Text getContent() {
        return content;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getEnvironment() {
        return environment;
    }

}
