/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package sa.sauditourism.employee.managers.language.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import sa.sauditourism.employee.constants.FirebaseConstants;


/**
 * Definition of ObjectType SupportedLanguages.
 *
 * @since 2024-04-16
 */
@PrimaryKeys({"id"})
public final class SupportedLanguages extends CloudDBZoneObject {
    private Integer id;

    @NotNull
    @DefaultValue(stringValue = "")
    private String code;

    @NotNull
    @DefaultValue(stringValue = "")
    private String flag;

    @NotNull
    @DefaultValue(stringValue = "")
    private String value;

    @DefaultValue(stringValue = "PROD")
    private String environment;

    private Text tabs;

    public SupportedLanguages() {
        super(SupportedLanguages.class);
        this.code = "";
        this.flag = "";
        this.value = "";
        this.environment = FirebaseConstants.REALTIME_DB_PROD_VALUE;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getFlag() {
        return flag;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getEnvironment() {
        return environment;
    }

    public void setTabs(Text tabs) {
        this.tabs = tabs;
    }

    public Text getTabs() {
        return tabs;
    }

}
