/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package sa.sauditourism.employee.configuration;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType AppConfigurations.
 *
 * @since 2024-08-04
 */
@PrimaryKeys({"id"})
public final class AppConfigurations extends CloudDBZoneObject {
    private Integer id;

    private String lang;

    private String environment;

    private Text content;

    public AppConfigurations() {
        super(AppConfigurations.class);
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    public String getLang() {
        return lang;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public String getEnvironment() {
        return environment;
    }

    public void setContent(Text content) {
        this.content = content;
    }

    public Text getContent() {
        return content;
    }

}
